# Generated by Django 2.2.9 on 2020-01-22 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForthGen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.TextField(blank=True, null=True)),
                ('dex', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('hg', models.IntegerField(blank=True, null=True)),
                ('ss', models.IntegerField(blank=True, null=True)),
                ('d', models.IntegerField(blank=True, null=True)),
                ('pe', models.IntegerField(blank=True, null=True)),
                ('pt', models.IntegerField(blank=True, null=True)),
                ('method', models.CharField(blank=True, max_length=45, null=True)),
                ('levelmin', models.IntegerField(blank=True, null=True)),
                ('levelmax', models.IntegerField(blank=True, null=True)),
                ('probdawn', models.IntegerField(blank=True, null=True)),
                ('probday', models.IntegerField(blank=True, null=True)),
                ('probnight', models.IntegerField(blank=True, null=True)),
                ('specialprob', models.CharField(blank=True, max_length=45, null=True)),
                ('subloc', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': '4gen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'images',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('place', models.TextField(blank=True, null=True)),
                ('dex', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('game', models.IntegerField(blank=True, null=True)),
                ('method', models.CharField(blank=True, max_length=45, null=True)),
                ('levelmin', models.IntegerField(blank=True, null=True)),
                ('levelmax', models.IntegerField(blank=True, null=True)),
                ('probdawn', models.IntegerField(blank=True, null=True)),
                ('probday', models.IntegerField(blank=True, null=True)),
                ('probnight', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'locations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokedex', models.CharField(blank=True, max_length=3000, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
